        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 08 15:12:14 2016
        MODULE DECISIONS__genmod
          INTERFACE 
            SUBROUTINE DECISIONS
            END SUBROUTINE DECISIONS
          END INTERFACE 
        END MODULE DECISIONS__genmod
