        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 08 15:12:14 2016
        MODULE PROD_SHARES__genmod
          INTERFACE 
            SUBROUTINE PROD_SHARES
            END SUBROUTINE PROD_SHARES
          END INTERFACE 
        END MODULE PROD_SHARES__genmod
