        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 08 15:12:13 2016
        MODULE SECOND__genmod
          INTERFACE 
            FUNCTION SECOND
              REAL(KIND=8) :: SECOND
            END FUNCTION SECOND
          END INTERFACE 
        END MODULE SECOND__genmod
