        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 08 15:12:14 2016
        MODULE SIMULATION__genmod
          INTERFACE 
            SUBROUTINE SIMULATION
            END SUBROUTINE SIMULATION
          END INTERFACE 
        END MODULE SIMULATION__genmod
