        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 08 15:12:13 2016
        MODULE ZUFALLRS__genmod
          INTERFACE 
            SUBROUTINE ZUFALLRS(SVBLK)
              REAL(KIND=8) :: SVBLK(*)
            END SUBROUTINE ZUFALLRS
          END INTERFACE 
        END MODULE ZUFALLRS__genmod
